name: Inject Tweak to IPA

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: 'IPA 다운로드 주소 입력'
        required: true
        default: 'https://iosvizor.net'
      dylib_url:
        description: 'DYLIB 도구 주소 입력'
        required: true
        default: 'https://raw.githubusercontent.com/test1ng-guy/iOS-sandbox-explorer/refs/heads/main/libShell.dylib'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python and System Dependencies
        run: |
          brew install ldid dpkg
          python3 -m pip install --upgrade pip
          python3 -m pip install pyzule-rw

      - name: Download Game and Tweak Files
        run: |
          curl -L "${{ github.event.inputs.ipa_url }}" -o original.ipa
          curl -L "${{ github.event.inputs.dylib_url }}" -o tweak.dylib

      - name: Safe Inject Tweak
        run: |
          pyzule -i original.ipa -o completed.ipa -f tweak.dylib

      - name: Upload Finished IPA
        uses: actions/upload-artifact@v4
        with:
          name: Patched-IPA-File
          path: completed.ipa
          curl -L "${{ github.event.inputs.ipa_url }}" -o original.ipa
          curl -L "${{ github.event.inputs.dylib_url }}" -o tweak.dylib

      - name: Inject Tweak into IPA
        run: |
          azule -i original.ipa -o patched.ipa -f tweak.dylib

      - name: Upload Finished IPA
        uses: actions/upload-artifact@v4
        with:
          name: Patched-IPA-File
          path: patched.ipa
